# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5f6d09fa767827fc9dd592210910c5e2875a6052759197653180fec59a756f3caa3b7dd32275bfe92eed679596e0bfd9b7957ff7dd84f81ffa43a3682bd5bbe5

test:
  secret_key_base: 33e50ad544704882a754f163abc39ad6aba5e63483ae1afaa814175f0895c3fb3238688565a1095a4e0d619a3855afcc8a7ad62209c47f388c23ebf94fff6b05

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
